export const items = [
	{
		title: "Astro",
		imgurl: "https://avatars.githubusercontent.com/u/44914786?s=48&v=4",
		desc: "一个现代化的静态站点生成框架",
		siteurl: "https://github.com/withastro/astro",
		tags: ["框架"],
	},
	{
		title: "Fuwari",
		imgurl:
			"https://gcore.jsdelivr.net/gh/Keduoli03/My_img@img/demo-avatar.png",
		desc: "基于 Astro 开发的静态博客模板",
		siteurl: "https://github.com/saicaca/fuwari",
		tags: ["主题"],
	},
	{
		title: "开往",
		imgurl: "https://www.travellings.cn/assets/travelling.png",
		desc: "让传统友链“活跃”，让网页相互接力，让流量相互流动，让网络开放起来",
		siteurl: "https://www.travellings.cn/",
		tags: ["组织"],
	},
	{
		title: "笔墨迹",
		imgurl: "https://gcore.jsdelivr.net/gh/Keduoli03/My_img@img/bimoji.webp",
		desc: "致敬还在写博客的我们！",
		siteurl: "https://blogscn.fun/",
		tags: ["组织"],
	},
	{
		title: "博友圈",
		imgurl: "https://www.boyouquan.com/assets/images/sites/logo/logo-small.png",
		desc: "博客人的朋友圈，博客收录与文章 RSS 聚合网站",
		siteurl: "https://www.boyouquan.com/home",
		tags: ["组织"],
	},
	{
		title: "天影大侠的小站",
		imgurl:
			"https://weavatar.com/avatar/7388ea4765a319d5f83fea61c3236384?s=1000",
		desc: "The Blog of SkyShadowHero!",
		siteurl: "https://blog.skyshadow.fun/",
		tags: ["友链"],
	},
	{
		title: "伊卡的记事本",
		imgurl: "https://ikamusume7.org/avatar.webp",
		desc: "又菜又爱学",
		siteurl: "https://ikamusume7.org",
		tags: ["友链"],
	},
	{
		title: "M次元",
		imgurl:
			"https://cravatar.com/avatar/e067b11317af75ad0eff9db62d927096?s=80&d=blank",
		desc: "小声记录小事",
		siteurl: "https://mmxza.com/",
		tags: ["友链"],
	},
	{
		title: "Mayx的博客",
		imgurl: "https://avatars0.githubusercontent.com/u/17966333",
		desc: "Mayx’s Home Page",
		siteurl: "https://mayx.gitlab.io/",
		tags: ["友链"],
	},
	{
		title: "JIPA233の小窝",
		imgurl: "https://jipa.moe/static/avatar.jpg",
		desc: "Deed divides beings into lower and higher ones.",
		siteurl: "https://jipa.moe",
		tags: ["友链", "已失联"],
	},
	{
		title: "岚天小窝",
		imgurl:
			"https://gravatar.ltya.top/avatar/5af06b461740fb2bd7467b8561399703?s=500",
		desc: "一只鸽子住在这里~",
		siteurl: "https://blog.ltya.top/",
		tags: ["友链"],
	},
	{
		title: "LineXic书屋",
		imgurl: "https://linexic.top/avatar.webp",
		desc: "难离难舍，想抱紧些",
		siteurl: "https://www.linexic.top/",
		tags: ["友链"],
	},
	{
		title: "独元殇",
		imgurl: "https://img1.ccgxk.com/ccgxk-oss/2025/05/202505191037317NTuR1.jpg",
		desc: "月光刚好，你在仰望，我们一起仰望",
		siteurl: "https://www.ccgxk.com",
		tags: ["友链"],
	},
	{
		title: "記緒漂流",
		imgurl: "https://ttio.cc/apple-touch-icon.png",
		desc: "記憶の川に、思いで漂う",
		siteurl: "https://ttio.cc",
		tags: ["友链"],
	},
	{
		title: "流月小站",
		imgurl: "https://cdn.flowmoon.cn/assets/img/avatar.png",
		desc: "且听风吟，静待花开",
		siteurl: "https://blog.flowmoon.cn/",
		tags: ["友链"],
	},
	{
		title: "Pinpe 的云端",
		imgurl: "https://pinpe.top/head.jpg",
		desc: "	一个属于自己的云朵。",
		siteurl: "https://pinpe.top/",
		tags: ["友链"],
	},
	{
		title: "wuxian's web",
		imgurl: "",
		desc: "你喜欢吃青椒吗？",
		siteurl: "https://alxian.cn/",
		tags: ["友链"],
	},
	{
		title: "酥米的小站",
		imgurl:
			"https://cdn.jsdmirror.com/gh/huang233893/blog-image-bed/top/huang233893/imgs/blog/userfb6a1018b84ce485.jpg",
		desc: "有朝一日，寻见梦中人✨",
		siteurl: "https://www.sumi233.top/",
		tags: ["友链"],
	},
];
