export const items = [
	{
		title: "Astro",
		imgurl: "https://avatars.githubusercontent.com/u/44914786?s=48&v=4",
		desc: "一个现代化的静态站点生成框架",
		siteurl: "https://github.com/withastro/astro",
		
		tags: ["框架"],
	},
	{
		title: "天影大侠的小站",
		imgurl:
			"https://weavatar.com/avatar/7388ea4765a319d5f83fea61c3236384?s=1000",
		desc: "The Blog of SkyShadowHero!",
		siteurl: "https://blog.skyshadow.fun/",
		rss:"https://blog.skyshadow.fun/rss.xml",
		tags: ["友链"],
	},
	{
		title: "伊卡的记事本",
		imgurl: "https://ikamusume7.org/avatar.webp",
		desc: "又菜又爱学",
		siteurl: "https://ikamusume7.org",
		rss:"https://ikamusume7.org/rss.xml",
		tags: ["友链"],
	},
	{
		title: "M次元",
		imgurl:
			"https://cravatar.com/avatar/e067b11317af75ad0eff9db62d927096?s=80&d=blank",
		desc: "小声记录小事",
		siteurl: "https://mmxza.com/",
		tags: ["友链"],
	},
	{
		title: "Mayx的博客",
		imgurl: "https://avatars0.githubusercontent.com/u/17966333",
		desc: "Mayx’s Home Page",
		siteurl: "https://mayx.gitlab.io/",
		rss:"https://mayx.gitlab.io/atom.xml",
		tags: ["友链"],
	},
	{
		title: "岚天小窝",
		imgurl:
			"https://gravatar.ltya.top/avatar/5af06b461740fb2bd7467b8561399703?s=500",
		desc: "一只鸽子住在这里~",
		siteurl: "https://blog.ltya.top/",
		rss:"https://blog.ltya.top/atom.xml",
		tags: ["友链"],
	},
	{
		title: "LineXic书屋",
		imgurl: "https://linexic.top/avatar.webp",
		desc: "难离难舍，想抱紧些",
		siteurl: "https://www.linexic.top/",
		rss:"https://www.linexic.top/rss.xml",
		tags: ["友链"],
	},
	{
		title: "独元殇",
		imgurl: "https://img1.ccgxk.com/ccgxk-oss/2025/05/202505191037317NTuR1.jpg",
		desc: "月光刚好，你在仰望，我们一起仰望",
		siteurl: "https://www.ccgxk.com",
		rss:"https://www.ccgxk.com/rss.php",
		tags: ["友链"],
	},
	{
		title: "記緒漂流",
		imgurl: "https://ttio.cc/favicon.svg",
		desc: "于记忆之川，泛思绪之舟",
		siteurl: "https://ttio.cc",
		rss:"https://ttio.cc/feed.xml",
		tags: ["友链"],
	},
	{
		title: "流月小站",
		imgurl: "https://cdn.liuyue.net/assets/img/avatar.jpg",
		desc: "且听风吟，静待花开",
		siteurl: "https://blog.flowmoon.cn/",
		rss:"https://blog.flowmoon.cn/rss.xml",
		tags: ["友链"],
	},
	{
		title: "Pinpe 的云端",
		imgurl: "https://pinpe.top/head.jpg",
		desc: "	一个属于自己的云朵。",
		siteurl: "https://pinpe.top/",
		rss:"https://pinpe.top/rss.xml",
		tags: ["友链"],
	},
	{
		title: "wuxian's web",
		imgurl: "",
		desc: "你喜欢吃青椒吗？",
		siteurl: "https://alxian.cn/",
		tags: ["友链"],
	},
	{
		title: "酥米的小站",
		imgurl:
			"https://cdn.jsdmirror.com/gh/huang233893/blog-image-bed/top/huang233893/imgs/blog/userfb6a1018b84ce485.jpg",
		desc: "有朝一日，寻见梦中人✨",
		siteurl: "https://www.sumi233.top/",
		rss:"https://www.sumi233.top/rss.xml",
		tags: ["友链"],
	},
	{
		title: "蘇 SU",
		imgurl: "https://suus.me/avatar.webp",
		desc: "在数字的海洋中，寻找属于自己的星辰。",
		siteurl: "https://suus.me/",
		rss:"https://suus.me/rss.xml",
		tags: ["友链"],
	},
	{
		title: "Evilrabbit Blog",
		imgurl: "https://blog.yujiay.wang/images/site/BlogHsvg.png",
		desc: "爱 Coding 爱生活",
		siteurl: "https://blog.yujiay.wang/",
		rss:"https://blog.yujiay.wang/atom.xml",
		tags: ["友链"],
	},
	{
		title: "两个笨笨",
		imgurl: "https://pan.mkirin.top/f/9Bt9/icon.png",
		desc: "两个笨笨的blog",
		siteurl: "https://mkirin.top",
		tags: ["友链"],
	},{
		title: '吐司气泡',
		imgurl: 'https://blog.toastbubble.top/avatar.webp',
		desc: '追求源于热爱',
		siteurl: 'https://blog.toastbubble.top/',
		tags: ['友链'],
	},
	{
		title: '懋和道人',
		imgurl: 'https://cn.cravatar.com/avatar/37d41e2b550633a30f5d41de61c1aa92?s=400&r=G&d=mp&ver=1754413756',
		desc: '李懋和，俗名李栋梁。书法、国画爱好者，互联网安全与前端建设者。',
		siteurl: 'https://www.dao.js.cn/',
		rss:"https://www.dao.js.cn/feed.php",
		tags: ['友链'],
	},

];
